In [2]:
print('Hello Guy')

Hello Guy


In [3]:
import numpy as np

In [4]:
#One dimentional array

arr = np.array([1, 2, 3])

In [5]:
arr

array([1, 2, 3])

In [6]:
type(arr)

numpy.ndarray

In [9]:
#Multi-dimentional Array

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [10]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr.shape

(3, 3)

In [14]:
arr.ndim

2

In [17]:
#Mathematical operations
x = np.array([[1 ,2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [19]:
x


array([[1, 2],
       [3, 4]])

In [20]:
y

array([[5, 6],
       [7, 8]])

In [ ]:
#Array Addition
x + y

array([[ 6,  8],
       [10, 12]])

In [22]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [ ]:
#Array Subtraction
x-y

array([[-4, -4],
       [-4, -4]])

In [24]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [26]:
#Array Multipication
x*y

array([[ 5, 12],
       [21, 32]])

In [28]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [29]:
#Array Division
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
#Squareroot of all elements inside the array
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [33]:
#Dot Product
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [35]:
#Transpose
h = x.T
h

array([[1, 3],
       [2, 4]])

In [36]:
h.T

array([[1, 2],
       [3, 4]])

In [37]:
#Sum rows of matrices
np.sum(x, axis=0)

array([4, 6])

In [38]:
#Sum entries of columns
np.sum(x, axis = 1)

array([3, 7])